### ISSUE TITLE
Add a share button to the ImageScreen

### ISSUE THREAD

**Issue by cryptoboid** [cryptoboid/mytag#18]

**Comment by barelyhuman** [comment]
I'd like to  pick this up.

**Comment by cryptoboid** [comment]
Thanks, I thought about a simple share button on the top right (why find the images by classification, if you can't share them?).

**Comment by barelyhuman** [comment]
Cool, I’ll start with this morning tomorrow, and the facebook request

**Comment by barelyhuman** [comment]
https://github.com/cryptoboid/mytag/pull/25

Raised. @cryptoboid

**Comment by cryptoboid** [comment]
Solved with #28
