### ISSUE TITLE
List all tags in Home, instead of using a picker

### ISSUE THREAD

**Issue by cryptoboid** [cryptoboid/mytag#30]
Instead of using a picker, present the user in Home screen with all available tags, similar to Google Photos: 
![](https://user-images.githubusercontent.com/77416692/112495924-3c2d6080-8d7c-11eb-9a8e-0034903a2aed.png)

For now, this change DOES NOT include a search bar feature, nor intelligently grouping tags under sections (People, Places, Things, etc...).

**Comment by cryptoboid** [comment]
Hey @barelyhuman, I've just finished the new design. If you want, you can check it out on iOS, I hope it works now!

**Comment by barelyhuman** [comment]
@cryptoboid Will as I find time, will also report back accordingly
